services:
  php:
    container_name: roller_coaster_php
    build: resources/docker/app
    image: roller_coaster_php_image
    volumes:
      - ./app:/var/www/html
      - ./app/writable/prod:/var/www/html/writable:rw
    working_dir: /var/www/html
    depends_on:
      - redis
    networks:
      - roller_coaster_network
    expose:
      - ${PHP_EXPOSE:-9000}
    env_file:
      - .env.production
    command: >
      sh -c "composer install --no-dev --prefer-dist --no-interaction --working-dir=/var/www/html && php-fpm"
  monitoring:
    container_name: roller_coaster_monitoring
    image: roller_coaster_php_image
    command: ["php", "spark", "coaster:checker"]
    volumes:
      - ./app:/var/www/html
      - ./app/writable/prod:/var/www/html/writable:rw
    working_dir: /var/www/html
    depends_on:
      - redis
      - php
    networks:
      - roller_coaster_network
    env_file:
      - .env.production
  nginx:
    image: nginx:latest
    container_name: roller_coaster_nginx
    restart: always
    volumes:
      - ./app:/var/www/html
      - ./app/writable/prod:/var/www/html/writable:rw
      - ./resources/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${NGINX_PORT:-8888}:80"
    depends_on:
      - php
    networks:
      - roller_coaster_network
  redis:
    image: redis:latest
    container_name: roller_coaster_redis
    restart: always
    ports:
      - "${REDIS_PORT:-6666}:6379"
    volumes:
      - ./resources/redis/data:/root/redis
      - ./resources/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - roller_coaster_network

networks:
  roller_coaster_network:
    driver: bridge